"""Initial commit

Revision ID: 4ede38e2b1b8
Revises: 
Create Date: 2026-07-26 19:28:50.440057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ede38e2b1b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('ref', sa.UUID(), nullable=False, comment='PK: UUID (Уникальный идентификатор кошелька)'),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False, comment='Numeric (Баланс кошелька)'),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currencyenum'), nullable=False, comment='Enum(Currency) - (Валюта)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='DateTime (Дата и время создания кошелька)'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='DateTime(Дата последней транзакции).'),
    sa.PrimaryKeyConstraint('ref')
    )
    op.create_table('transactions',
    sa.Column('ref', sa.UUID(), nullable=False, comment='PK: UUID (Уникальный идентификатор транзакции)'),
    sa.Column('wallet_ref', sa.UUID(), nullable=False, comment='FK: UUID(Кошелек в котором прошла транзакция)'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Numeric (Размер транзакции)'),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAW', name='transactiontypeenum'), nullable=False, comment='Enum(TransactionTypeEnum) - (Тип Транзакции)'),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transactionstatusenum'), nullable=False, comment='Enum(TransactionStatusEnum) - (Статус Транзакции)'),
    sa.Column('description', sa.String(length=50), nullable=True, comment='String (Комментарий к транзакции)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='DateTime (Дата и время проведения транзакции)'),
    sa.ForeignKeyConstraint(['wallet_ref'], ['wallets.ref'], ),
    sa.PrimaryKeyConstraint('ref')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('wallets')
    # ### end Alembic commands ###
